apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-frontend.fullname" . }}-config
  labels:
    {{- include "todo-frontend.labels" . | nindent 4 }}
data:
  API_BASE_URL: "http://todo-backend.todo.svc.cluster.local:8000"
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
