apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-backend.fullname" . }}-config
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  ENVIRONMENT: {{ .Values.env.ENVIRONMENT | quote }}
